# Generated by Django 2.1.5 on 2019-01-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingStall',
            fields=[
                ('availability', models.BooleanField(default=False)),
                ('price', models.FloatField(default=10, verbose_name='Hourly rate')),
                ('managerInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='managers', serialize=False, to='api.Manager')),
            ],
        ),
    ]
