# Generated by Django 2.1.5 on 2019-02-25 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20190224_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='users',
        ),
        migrations.AddField(
            model_name='userpin',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pin_entries', to='api.Device'),
        ),
        migrations.AddField(
            model_name='userpin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
