# Generated by Django 2.1.5 on 2019-01-27 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parkingstall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=datetime.datetime(2019, 1, 27, 12, 25, 31, 503629))),
                ('endTime', models.DateTimeField(blank=True)),
                ('cost', models.FloatField()),
                ('hasPaid', models.BooleanField(default=False)),
                ('isLegalSession', models.BooleanField()),
                ('customerInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('parkingStall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ParkingStall')),
            ],
        ),
    ]
