# Generated by Django 2.1.5 on 2019-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parkingsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerInformation',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='managerInformation',
        ),
        migrations.RemoveField(
            model_name='parkingstall',
            name='managerInformation',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='customerInformation',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='hasPaid',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='parkingStall',
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='plateNo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='price',
            field=models.FloatField(default=10, verbose_name='Hourly rate'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='startTime',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='ParkingStall',
        ),
    ]
