# Generated by Django 2.1.5 on 2019-02-27 21:19

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190227_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='info',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
