# Generated by Django 2.1.5 on 2019-02-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashlog',
            name='recorded_crash',
            field=models.TextField(),
        ),
    ]
