# Generated by Django 2.1.5 on 2019-03-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_userinfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='emergency_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
