# Generated by Django 2.1.5 on 2019-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userinfo_emergency_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='license_plate',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
