# Generated by Django 2.1.5 on 2019-04-02 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_userinfo_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashlog',
            name='attending_emergency_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crash_logs_attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crashlog',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('inprogress', 'inprogress'), ('done', 'done')], default='open', max_length=12),
        ),
    ]
