# Generated by Django 2.1.5 on 2019-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190402_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashlog',
            name='status',
        ),
        migrations.AddField(
            model_name='crashlog',
            name='state',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'inprogress'), (2, 'done')], default=0),
        ),
    ]
